//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bluepath.Services
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IExecutor")]
    public interface IExecutor
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/Execute", ReplyAction = "http://tempuri.org/IExecutor/ExecuteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void Execute(object[] parameters);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/Execute", ReplyAction = "http://tempuri.org/IExecutor/ExecuteResponse")]
        System.Threading.Tasks.Task ExecuteAsync(object[] parameters);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/Join", ReplyAction = "http://tempuri.org/IExecutor/JoinResponse")]
        void Join();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/Join", ReplyAction = "http://tempuri.org/IExecutor/JoinResponse")]
        System.Threading.Tasks.Task JoinAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/GetResult", ReplyAction = "http://tempuri.org/IExecutor/GetResultResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object GetResult();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IExecutor/GetResult", ReplyAction = "http://tempuri.org/IExecutor/GetResultResponse")]
        System.Threading.Tasks.Task<object> GetResultAsync();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExecutorChannel : IExecutor, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutorClient : System.ServiceModel.ClientBase<IExecutor>, IExecutor
    {

        public ExecutorClient()
        {
        }

        public ExecutorClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ExecutorClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ExecutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ExecutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public void Execute(object[] parameters)
        {
            base.Channel.Execute(parameters);
        }

        public System.Threading.Tasks.Task ExecuteAsync(object[] parameters)
        {
            return base.Channel.ExecuteAsync(parameters);
        }

        public void Join()
        {
            base.Channel.Join();
        }

        public System.Threading.Tasks.Task JoinAsync()
        {
            return base.Channel.JoinAsync();
        }

        public object GetResult()
        {
            return base.Channel.GetResult();
        }

        public System.Threading.Tasks.Task<object> GetResultAsync()
        {
            return base.Channel.GetResultAsync();
        }
    }
}